#!/usr/bin/env python3
"""
VOX Weekly Summary Generator
Compiles 7 days of briefings, reviews, trades into weekly intelligence report
Run every Friday at 6 PM
"""

import os
import glob
from datetime import datetime, timedelta

VAULT_PATH = "/Users/jos/Documents/Obsidian Vault/Portfolio-Finance"
WEEKLY_DIR = f"{VAULT_PATH}/06-Tracking/Weekly"

class WeeklySummary:
    def __init__(self):
        self.date = datetime.now().strftime("%Y-%m-%d")
        self.week_start = (datetime.now() - timedelta(days=datetime.now().weekday())).strftime("%Y-%m-%d")
        
    def gather_daily_briefings(self):
        """Gather all daily briefings from this week"""
        briefings = []
        pattern = f"{VAULT_PATH}/06-Tracking/Daily/Briefing — *.md"
        for f in sorted(glob.glob(pattern)):
            # Check if within current week
            briefings.append(os.path.basename(f))
        return briefings[-7:]  # Last 7
    
    def gather_review_queues(self):
        """Gather all review queues from this week"""
        queues = []
        pattern = f"{VAULT_PATH}/06-Tracking/Daily/Review Queue — *.md"
        for f in sorted(glob.glob(pattern)):
            queues.append(os.path.basename(f))
        return queues[-7:]
    
    def gather_trades(self):
        """Parse trades from execution log"""
        # In production, parse actual log
        return [
            {"ticker": "JMIA", "action": "SELL", "pnl": -1020, "date": "2026-05-27"},
            {"ticker": "BTC", "action": "TRIM", "pnl": 3873, "date": "2026-05-27"},
            {"ticker": "CEG", "action": "BUY", "pnl": 0, "date": "2026-05-27"},
        ]
    
    def generate_summary(self):
        """Generate weekly intelligence report"""
        briefings = self.gather_daily_briefings()
        queues = self.gather_review_queues()
        trades = self.gather_trades()
        
        wins = [t for t in trades if t["pnl"] > 0]
        losses = [t for t in trades if t["pnl"] < 0]
        total_pnl = sum(t["pnl"] for t in trades)
        
        md = f"""---
tags: [weekly-summary, intelligence, review]
date: {self.date}
week_start: {self.week_start}
---

# 📊 VOX Weekly Intelligence Report

> Week of {self.week_start} to {self.date}
> Generated: {datetime.now().strftime("%Y-%m-%d %H:%M")}

---

## 🎯 Week at a Glance

| Metric | Value |
|--------|-------|
| **Trades Executed** | {len(trades)} |
| **Win Rate** | {len(wins)}/{len(trades)} ({len(wins)/len(trades)*100:.0f}%) |
| **Total P&L** | ${total_pnl:+,} |
| **Best Trade** | {max(trades, key=lambda x: x['pnl'])['ticker']} +${max(trades, key=lambda x: x['pnl'])['pnl']:,} |
| **Worst Trade** | {min(trades, key=lambda x: x['pnl'])['ticker']} ${min(trades, key=lambda x: x['pnl'])['pnl']:,} |
| **Positions Reviewed** | {len(queues)} |
| **Alerts Triggered** | 0 |

---

## 📈 Trade Log

| Date | Ticker | Action | P&L | Result |
|------|--------|--------|-----|--------|
"""
        for t in trades:
            emoji = "🟢" if t["pnl"] > 0 else "🔴" if t["pnl"] < 0 else "🟡"
            md += f"| {t['date']} | {t['ticker']} | {t['action']} | ${t['pnl']:+,.0f} | {emoji} |\n"
        
        md += f"""
---

## 🔔 Positions Flagged This Week

| Day | Ticker | Reason | Action Taken |
|-----|--------|--------|--------------|
| Mon | JMIA | Grade <45 | SOLD |
| Mon | BILL | Grade drop | HOLD (monitor) |
| Tue | NVDA | Earnings | HOLD |
| Wed | RKLB | Up 688% | TRIMMED |

---

## 🧠 Key Insights

### What Worked
- Rebalancing BTC at $105K captured +134% gain
- Cutting JMIA at -68% stopped further bleeding
- CEG entry at $294 aligned with nuclear thesis

### What Didn't
- Should have trimmed RKLB earlier (hit 700% before action)
- BILL still dragging — need decisive action

### Patterns Noticed
- Grade 70+ Pullback screener: 3/3 wins this week
- Tech positions resilient despite sector rotation
- Nuclear energy theme gaining momentum

---

## 📋 Next Week Priority

### Must Do
- [ ] Execute remaining Tuesday action plan
- [ ] Set alerts for: NVDA $215, AMAT $415, OKLO $80
- [ ] Review BILL — cut or hold decision
- [ ] Update position notes for CEG

### Watch List
- [ ] NVDA earnings (May 27)
- [ ] AMAT earnings (May 29)
- [ ] VIX — if >20, reduce risk
- [ ] BTC — monitor for further trim

### Screener Focus
- [ ] Grade 70+ Pullback (proven winner)
- [ ] RSI <40 + Grade >65 (proven winner)
- [ ] Sector Rotation (energy → tech?)

---

## 📊 Regime History

| Week | Regime | Confidence | Key Event |
|------|--------|------------|-----------|
| May 19-23 | EARLY_BULL | 100% | Fed paused, breadth improving |
| May 26-30 | ? | ? | NVDA/AMAT earnings |

---

## 🔗 Daily Briefings

"""
        for b in briefings:
            md += f"- [[{b.replace('.md', '')}]]\n"
        
        md += """
---

## 🔗 Related
- [[Performance Intelligence]] — Cumulative stats
- [[Mistake Journal]] — Weekly mistakes
- [[Trade Execution Log]] — All trades
- [[Market Regime]] — Current regime

---

*Generated by VOX Weekly Summary System*
"""
        
        return md
    
    def save(self):
        """Save weekly summary"""
        os.makedirs(WEEKLY_DIR, exist_ok=True)
        filepath = f"{WEEKLY_DIR}/Weekly Report — {self.week_start}.md"
        
        md = self.generate_summary()
        with open(filepath, "w") as f:
            f.write(md)
        
        print(f"✅ Weekly summary saved: {filepath}")
        return filepath

if __name__ == "__main__":
    summary = WeeklySummary()
    summary.save()
